substitutions:
  hostname: 'esppir2'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  manual_ip:
    static_ip: 192.168.20.27
    gateway: 192.168.20.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.20.4'
  username: !secret mqtt_user
  password: !secret mqtt_password
  will_message:  # disabled to avoid "Unavailable" during deep sleep

ota:
  password: !secret ota_password

logger:
  level: DEBUG
  
esphome:
  name: $hostname
  platform: ESP32
  board: esp32dev
  on_boot:
    priority: 200 # mqtt connected
    then:
      # we loose the PIR ON message that awakens us
      # but we still get the PIR OFF as soon as we listen for messages (so its only ON very briefly)
      - mqtt.publish:  # toggle PIR ON in the UI
          topic: ${hostname}/binary_sensor/${hostname}_pir/state
          payload: 'ON'
      - switch.turn_on: ${hostname}_awake
#     comment out following line after successfully adding to HA. Having it automatically entering deep sleep prior to that is a pain
      - switch.turn_on: ${hostname}_stay_awake
      - script.execute: sleep_timer
      
switch:
  - platform: gpio
    id: ${hostname}_stay_awake
    name: $hostname Stay Awake # turn on from UI to prevent deep sleep e.g. for OTA update
    pin: GPIO32
  - platform: gpio
    id: ${hostname}_awake
    name: $hostname Awake # turn on to indicate awake
    pin: GPIO33
    restore_mode: ALWAYS_OFF
  - platform: restart
    name: $hostname Restart

sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal

binary_sensor:
  - platform: gpio
    id: ${hostname}_pir
    name: $hostname PIR
    pin: GPIO39
    on_state: # on any state change
      then:
        - script.execute: sleep_timer

script:
  - id: sleep_timer
    mode: restart
    then:
      - delay: 10s
      - if:
          condition:
            and:
              - switch.is_off: ${hostname}_stay_awake
              - binary_sensor.is_off: ${hostname}_pir
          then:
            - switch.turn_off: ${hostname}_awake
            - delay: 300ms # else awake off not reflected in UI. 100ms is insufficient
            - deep_sleep.enter:
               id: sleeper
          else:
            - script.execute: sleep_timer

deep_sleep:
  id: sleeper
  wakeup_pin: GPIO39
  wakeup_pin_mode: IGNORE

